[package]
name = "tax_calc"
version = "0.1.0"
authors = ["segfo <k.segfo@gmail.com>"]
edition = "2018"

[dependencies]
libloading = "0.5"
kernel32-sys = "0.2.2"
winapi = "0.3.6"
log = "0.4"
log4rs = { version = "0.8.1", features = ["toml_format"] }
#libc = "0.2.46"